spring:
  application:
    name: "configserver"
  profiles:
    active: prod
  cloud:
    config:
      server:
        git:
          uri: ${MYBANK_CONFIG}
          default-label: "main"
          timeout: 5
          clone-on-start: true
          force-pull: true
    bus:
      id: ${spring.application.name}:${spring.profiles.active}
      enabled: true
  kafka:
    bootstrap-servers: kafka:9092

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "14E44C27368423AC2EB3598291D44"
